codestates-seb/seb40_main_033

- server/.gitignore
- server/.gradle/buildOutputCleanup/cache.properties
- server/src/main/java/server/team33/login/handler/UserAuthSuccessHandler.java
- server/src/main/java/server/team33/user/controller/UserController.java
- server/src/main/java/server/team33/user/service/UserService.java
Issue Number: N/A
<br>
- .gitignore 파일 설정
<br>
<br>
> [Server] .gitignore 파일 설정

- server/src/main/java/server/team33/item/controller/ItemController.java
- server/src/main/java/server/team33/item/dto/ItemDto.java
- server/src/main/java/server/team33/item/entity/Item.java
- server/src/main/java/server/team33/item/mapper/ItemMapper.java
- server/src/main/java/server/team33/item/service/ItemService.java
Issue Number: N/A
<br>
상품 등록 기능 추가되었습니다.
<br>
<br>
> 상품 등록 기능 구현

- client/.eslintrc.json
- client/package-lock.json
- client/package.json
- client/src/App.js
- client/src/assets/style/GlobalStyle.js
- client/src/assets/style/GlobalVariables.js
- client/src/components/Buttons/DefaultButton.js
- client/src/components/Buttons/LetterButton.js
- client/src/components/Buttons/PurpleButton.js
Issue Number: #19 
<br>
기본버튼, 글씨버튼 구현했습니다.
<br>
width, height, onClick, borderRadius 를 속성으로 커스텀 할 수 있다.
ex) 
```html
<LightPurpleButton width="300px" height="100px">버튼예시</LightPurpleButton>
```
<br>
> 💄 design: 버튼 컴포넌트 UI 구현 #19

- client/.gitignore
- client/src/components/Buttons/CounterButton.js
- client/src/components/Buttons/WishlistButton.js
- client/src/index.js
Issue Number: #19 
<br>
위시리스트 버튼 구현 및 gitignore 파일에 AppDev.js를 추가했습니다. 
<br>
<br>
> [Client] 위시리스트버튼 컴포넌트 UI 구현 & gitignore파일 수정

- server/src/main/java/server/team33/cart/dto/ItemCartDto.java
- server/src/main/java/server/team33/cart/entity/ItemCart.java
- server/src/main/java/server/team33/cart/mapper/CartMapper.java
- server/src/main/java/server/team33/cart/mapper/ItemCartMapper.java
- server/src/main/java/server/team33/exception/bussiness/ExceptionCode.java
- server/src/main/java/server/team33/item/dto/ItemSimpleResponseDto.java
- server/src/main/java/server/team33/item/mapper/ItemMapper.java
- server/src/main/java/server/team33/order/controller/OrderController.java
- server/src/main/java/server/team33/order/dto/ItemOrderDto.java
- server/src/main/java/server/team33/order/dto/OrderDto.java
- server/src/main/java/server/team33/order/entity/ItemOrder.java
- server/src/main/java/server/team33/order/entity/Order.java
- server/src/main/java/server/team33/order/entity/OrderStatus.java
- server/src/main/java/server/team33/order/mapper/ItemOrderMapper.java
- server/src/main/java/server/team33/order/mapper/OrderMapper.java
- server/src/main/java/server/team33/order/reposiroty/ItemOrderRepository.java
- server/src/main/java/server/team33/order/reposiroty/OrderRepository.java
- server/src/main/java/server/team33/order/service/ItemOrderService.java
- server/src/main/java/server/team33/order/service/OrderService.java
- server/src/main/java/server/team33/user/entity/User.java
Issue Number: #36 #24 
<br>
- 주문하기
- 주문 목록 조회
- 주문의 상세 내역 조회
- 주문 취소
<br>
<br>
> [Server] 주문 기능 구현

- server/src/main/java/server/team33/order/service/OrderService.java
Issue Number: #36 
<br>
- 주문 객체의 itemOrder 를 불러오지 못하는 오류를 수정했습니다.
<br>
<br>
> [Server] ItemOrder 객체를 불러오지 못하는 오류 수정

- client/src/components/Buttons/WishlistButton.js
- client/src/components/Lists/DefaultLIst.js
- client/src/components/Lists/ListCards.js
Issue Number:  #19 
<br>
리스트목록 컴포넌트가 추가되었습니다.
기존의 WishlistButton.js에는 z-index가 추가되었으니 인지해주시기 바랍니다.
또한 ListCards라는 컴포넌트가 새로 생겼는데, 이는 나중에 페이지를 제작할 때 더 쉽게 하려는 의도를 가지고 만들었으나,  단독 제작에는 실패하여 후에 여러분의 많은 참여 부탁드립니다.
<br>
<br>
> [Client]  리스트목록 컴포넌트 UI 구현

- server/src/main/java/server/team33/category/controller/ItemCategoryController.java
- server/src/main/java/server/team33/category/dto/CategoryDto.java
- server/src/main/java/server/team33/category/entity/Category.java
- server/src/main/java/server/team33/category/entity/ItemCategory.java
- server/src/main/java/server/team33/category/mapper/CategoryMapper.java
- server/src/main/java/server/team33/category/repository/CategoryRepository.java
- server/src/main/java/server/team33/category/service/CategoryService.java
- server/src/main/java/server/team33/item/controller/ItemController.java
- server/src/main/java/server/team33/item/dto/ItemDto.java
- server/src/main/java/server/team33/item/entity/Item.java
- server/src/main/java/server/team33/item/mapper/ItemMapper.java
- server/src/main/java/server/team33/item/repository/ItemRepository.java
- server/src/main/java/server/team33/review/entity/Review.java
- server/src/main/java/server/team33/talk/entity/Talk.java
- server/src/main/java/server/team33/talk/entity/TalkComment.java
Issue Number: #29 
<br>
- 기능별 카테고리 분할 기능 구현
- ResponseDtoClass 이름 변경 및, ItemDto 코드추가
<br>
<br>
> [Server] 기능별 카테고리 분할 기능 구현

- server/src/main/java/server/team33/login/config/SecurityConfig.java
- server/src/main/java/server/team33/login/handler/UserAuthSuccessHandler.java
- server/src/main/java/server/team33/order/controller/OrderController.java
- server/src/main/java/server/team33/order/service/OrderService.java
- server/src/main/java/server/team33/payment/contoller/PaymentController.java
- server/src/main/java/server/team33/payment/dto/GeneralPayDto.java
- server/src/main/java/server/team33/payment/dto/KakaoPayApproveDto.java
- server/src/main/java/server/team33/payment/dto/KakaoPayRequestDto.java
- server/src/main/java/server/team33/payment/service/PayService.java
- server/src/main/java/server/team33/user/entity/User.java
- server/src/main/webapp/index.html
Issue Number: #42, #30
<br>
- 카카오 페이 결제 기능 완성
<br>
<br>
> [Server] 결제 기능 완성

- server/src/main/java/server/team33/exception/bussiness/ExceptionCode.java
- server/src/main/java/server/team33/item/mapper/ItemMapper.java
- server/src/main/java/server/team33/order/dto/OrderDto.java
- server/src/main/java/server/team33/order/mapper/OrderMapper.java
- server/src/main/java/server/team33/order/reposiroty/OrderRepository.java
- server/src/main/java/server/team33/order/service/OrderService.java
- server/src/main/java/server/team33/payment/contoller/PaymentController.java
- server/src/main/java/server/team33/review/controller/ReviewController.java
- server/src/main/java/server/team33/review/dto/ReviewDto.java
- server/src/main/java/server/team33/review/dto/ReviewResponseDto.java
- server/src/main/java/server/team33/review/entity/Review.java
- server/src/main/java/server/team33/review/mapper/ReviewMapper.java
- server/src/main/java/server/team33/review/repository/ReviewRepository.java
- server/src/main/java/server/team33/review/service/ReviewService.java
Issue Number: #38 
<br>
- 리뷰 등록하기
- 리뷰 수정하기
- 리뷰 삭제하기
- 유저의 리뷰 조회하기
<br>
- 아이템 구매자만 해당 아이템에 대한 리뷰를 작성할 수 있습니다.
- 리뷰 작성자만 리뷰를 수정하고 삭제할 수 있습니다.
<br>
> [Server] 리뷰 기능 구현

- server/src/main/java/server/team33/order/dto/OrderDto.java
- server/src/main/java/server/team33/order/entity/Order.java
- server/src/main/java/server/team33/order/mapper/OrderMapper.java
- server/src/main/java/server/team33/order/service/ItemOrderService.java
- server/src/main/java/server/team33/order/service/OrderService.java
Issue Number: #24 
<br>
- Order entity 에 totalQuantity 를 추가했습니다.
- OrderService 에 totalQuantity 의 값을 구하는 메서드를 추가했습니다.
<br>
<br>
> [Server] 결제 요청시 상품의 총 개수를 파악할 수 있도록 totalQuantity 필드 추가

- server/src/main/java/server/team33/login/config/CustomFilterConfigurer.java
- server/src/main/java/server/team33/login/config/SecurityConfig.java
- server/src/main/java/server/team33/login/handler/UserAuthSuccessHandler.java
- server/src/main/java/server/team33/payment/service/PayService.java
- server/src/main/java/server/team33/user/controller/UserController.java
- server/src/main/webapp/login.html
Issue Number: #30, #5
<br>
- 카카오페이 결제 시 상품 이름 수정
- 일반 로그인 토큰 전달 확인(확인은 했지만 프론트 엔드와 테스트 해봐야 함)
<br>
- 소셜로그인을 위한 html파일 추가
<br>
> [Server] 카카오페이 결제 시 상품 이름 수정, 일반 로그인 토큰 테스트

- .gitignore
- client/package-lock.json
- client/src/components/Buttons/SortButton.js
Issue Number: #19
<br>
정렬버튼 UI를 구현했습니다. 글씨버튼은 기현님이 만드신 LetterButtonColor 컴포넌트를 가져다가 썼습니다. 해당 컴포넌트에 focus에 대한 부분은 작성되어 있지 않아 제가 정렬버튼컴포넌트에서 추가했습니다. 아직까지 글씨버튼들의 구체적인 기능은 없지만, 후에 페이지를 만드시면서 기능들을 채워넣으면 될 듯합니다.
또한 gitignore 를 최상위 폴더에 만들어 ds store가 추적되지 않게 했습니다!
<br>
<br>
> [Client] 정렬버튼 컴포넌트 UI 구현

- client/src/components/ItemSummary.js/Summary.js
- client/src/components/Pagination.js
- client/src/components/Tabs/DefaultTabButton.js
- client/src/components/Tabs/TabButtons.js
Issue Number: #19
<br>
페이지네이션 버튼 및 탭 버튼을 수정했습니다.
<br>
<br>
> [Client] 페이지네이션 컴포넌트 UI 구현 

- client/package-lock.json
- client/package.json
- client/src/components/Buttons/PurpleButton.js
- client/src/components/Etc/PageTitle.js
- client/src/components/Etc/Price.js
- client/src/components/Etc/RecommendedTitle.js
- client/src/components/Forms/DefalutForm.js
- client/src/components/Forms/ReviewForm.js
- client/src/components/Forms/TalkForm.js
- client/src/components/Forms/UpdateTalkForm.js
- client/src/components/LeftNav.js
- client/src/components/Modals/DefalutModal.js
- client/src/components/Modals/DeleteAccountModal.js
- client/src/components/Modals/GoodbyeModal.js
- client/src/components/Modals/OrderCompleteModal.js
- client/src/components/Modals/ReviewModal.js
- client/src/components/Modals/TalkModal.js
- client/src/components/Modals/WelcomeModal.js
- client/src/components/Modals/style.css
- client/src/components/Stars/BtnStar.js
- client/src/components/Stars/TextStar.js
Issue Number: #19 
<br>
- 모달 컴포넌트 UI 구현
- 폼 컴포넌트 UI 구현
- 기타 컴포넌트 UI 구현
<br>
<br>
> [Client] 모달, 폼 컴포넌트 UI 구현

- server/src/main/java/server/team33/cart/mapper/ItemCartMapper.java
- server/src/main/java/server/team33/item/dto/ItemDto.java
- server/src/main/java/server/team33/item/entity/Item.java
- server/src/main/java/server/team33/item/mapper/ItemMapper.java
- server/src/main/java/server/team33/order/mapper/ItemOrderMapper.java
- server/src/main/java/server/team33/review/controller/ReviewController.java
- server/src/main/java/server/team33/review/dto/ReviewDetailResponseDto.java
- server/src/main/java/server/team33/review/mapper/ReviewMapper.java
- server/src/main/java/server/team33/review/repository/ReviewRepository.java
- server/src/main/java/server/team33/review/service/ReviewService.java
Issue Number: #53 #24 
<br>
- 리뷰 별점 평균 계산 및 갱신
- 단건 주문시 정기 구독 주문과 일반 주문이 분기가 되지 않는 오류 수정
<br>
<br>
> [Server] 리뷰 별점 평균 계산 및 갱신

- server/src/main/java/server/team33/category/controller/CategoryController.java
- server/src/main/java/server/team33/item/mapper/ItemMapper.java
- server/src/main/java/server/team33/item/repository/ItemRepository.java
- server/src/main/java/server/team33/item/service/ItemService.java
Issue Number: #29 
<br>
- 카테고리별 아이템 조회 기능을 수정했습니다.
<br>
<br>
> [Server] 카테고리별 아이템 조회 기능 수정

- server/src/main/java/server/team33/exception/bussiness/ExceptionCode.java
- server/src/main/java/server/team33/talk/controller/TalkCommentController.java
- server/src/main/java/server/team33/talk/controller/TalkController.java
- server/src/main/java/server/team33/talk/dto/TalkAndCommentDto.java
- server/src/main/java/server/team33/talk/dto/TalkCommentDto.java
- server/src/main/java/server/team33/talk/dto/TalkDetailResponseDto.java
- server/src/main/java/server/team33/talk/dto/TalkDto.java
- server/src/main/java/server/team33/talk/dto/TalkOrCommentDto.java
- server/src/main/java/server/team33/talk/dto/TalkResponseDto.java
- server/src/main/java/server/team33/talk/entity/Talk.java
- server/src/main/java/server/team33/talk/entity/TalkComment.java
- server/src/main/java/server/team33/talk/mapper/TalkMapper.java
- server/src/main/java/server/team33/talk/repository/TalkCommentRepository.java
- server/src/main/java/server/team33/talk/repository/TalkRepository.java
- server/src/main/java/server/team33/talk/service/TalkCommentService.java
- server/src/main/java/server/team33/talk/service/TalkService.java
Issue Number: #55 
<br>
- 토크 CRUD 구현
- 토크 코멘트 CRUD 구현
- 유저별 토크 및 토크 코멘트 모아보기 구현
<br>
<br>
> [Server] Talk & TalkComment 기능 구현

- client/.gitignore
- client/src/components/Layout/Layout.js
- client/src/components/Layout/LeftNav.js
- client/src/components/Layout/RightNav.js
- client/src/index.js
Issue Number: #19 #67 #66
<br>
- 상하단에 마진 값을 추가하였습니다.
- Nav Position에 sticky를 추가하였습니다.
- AppDev 관련 코드를 삭제하였습니다.
<br>
<br>
> [Client] 상하단 margin 추가 및 Nav sticky 추가

- server/src/main/java/server/team33/category/controller/CategoryController.java
- server/src/main/java/server/team33/category/entity/Category.java
- server/src/main/java/server/team33/item/entity/Item.java
- server/src/main/java/server/team33/item/repository/ItemRepository.java
- server/src/main/java/server/team33/item/service/BrandService.java
- server/src/main/java/server/team33/item/service/ItemService.java
- server/src/main/java/server/team33/user/entity/User.java
- server/src/main/java/server/team33/wish/controller/WishController.java
- server/src/main/java/server/team33/wish/dto/WishResponseDto.java
- server/src/main/java/server/team33/wish/entity/Wish.java
- server/src/main/java/server/team33/wish/mapper/WishMapper.java
- server/src/main/java/server/team33/wish/repository/WishRepository.java
- server/src/main/java/server/team33/wish/service/WishService.java
Issue Number:  #29 
<br>
<br>
카테고리별 브랜드별 모아보기 기능, 찜 기능 구현 1.0
<br>
> [Server] 카테고리별 브랜드별 모아보기 기능

- server/src/main/java/server/team33/category/controller/CategoryController.java
- server/src/main/java/server/team33/item/mapper/ItemMapper.java
- server/src/main/java/server/team33/item/repository/ItemRepository.java
- server/src/main/java/server/team33/item/service/ItemService.java
Issue Number: #82 
<br>
카테고리별로 할인을 모아볼 수 있는 기능, 카테고리 브랜드별로 할인을 모아볼 수 있는 기능 추가
<br>
> [Server] 할인 모아보기 기능 구현 

- server/src/main/java/server/team33/order/service/ItemOrderService.java
- server/src/main/java/server/team33/scheduler/config/Config.java
- server/src/main/java/server/team33/scheduler/controller/SchedulingController.java
- server/src/main/java/server/team33/scheduler/service/SchedulingService.java
- server/src/main/java/server/team33/scheduler/service/SubscriptionService.java
- server/src/main/java/server/team33/user/dto/UserDto.java
- server/src/main/java/server/team33/user/entity/User.java
- server/src/main/java/server/team33/user/mapper/UserMapper.java
- server/src/main/java/server/team33/user/service/UserService.java
Issue Number: #21 #22
<br>
detailAddress 필드 및 mapper, dto 추가
회원 정보, 회원 수정, 회원 정보 추가 기입 수정
<br>
<br>
> [Server] detailAddress 필드 및 mapper, dto 추가

- client/src/components/Buttons/DefaultButton.js
- client/src/components/Buttons/PurpleButton.js
- client/src/components/Inputs/AuthForm.js
- client/src/components/Inputs/AuthInput.js
- client/src/pages/SignUp.js
Issue Number: #86 
<br>
<br>
<br>
> [Client] 회원가입 페이지 주소 라이브러리 연결 외

- server/src/main/java/server/team33/item/entity/Item.java
- server/src/main/java/server/team33/item/repository/ItemRepository.java
- server/src/main/java/server/team33/wish/controller/WishController.java
- server/src/main/java/server/team33/wish/dto/WishResponseDto.java
- server/src/main/java/server/team33/wish/entity/Wish.java
- server/src/main/java/server/team33/wish/mapper/WishMapper.java
- server/src/main/java/server/team33/wish/repository/WishRepository.java
- server/src/main/java/server/team33/wish/service/WishService.java
Issue Number: #72 
<br>
로그인한 회원의 찜하기 기능 추가
<br>
> :sparkles: feat: 로그인한 회원의 찜하기 기능 구현 

- client/src/components/Buttons/SearchButtons/SortButton.js
- client/src/components/ItemSummary/Summary.js
- client/src/pages/MyPages/UserInfo.js
Issue Number: #83 
<br>
마이페이지에서 회원정보수정 페이지를 구현했습니다. 이후엔 api가 완성된 후, 다시 해야합니다.
<br>
<br>
> [Client] 마이페이지-회원정보수정 페이지 목데이터 구현

- client/src/Router.js
- client/src/components/Etc/PayInfo.js
- client/src/components/Etc/Price.js
- client/src/components/Layout/RightNav.js
- client/src/components/Lists/MyPageLists/OrderDetailList.js
- client/src/components/Lists/MyPageLists/OrderList.js
- client/src/components/Tabs/MypageTab.js
- client/src/pages/MyPages/NormalOrder.js
- client/src/pages/MyPages/OrderDetail.js
- client/src/pages/MyPages/SubscriptionOrder.js
Issue Number: #84 #85 #100
<br>
- 주문내역 상세 페이지 UI를 구현하였습니다.
- 가격 컴포넌트에 할인가(결제정보)를 추가하여 보완하였습니다.
- 배송지정보 및 결제정보 컴포넌트를 구현하였습니다. (components/Etc/PayInfo.js)
<br>
<br>
> [Client] 주문내역 상세 페이지 UI 구현

- client/src/components/Caroucel/MainCaroucel.js
- client/src/components/Caroucel/slick-theme.css
- client/src/components/Inputs/AuthForm.js
- client/src/components/Inputs/AuthInput.js
- client/src/components/Layout/Layout.js
- client/src/components/Modals/AddressModal.js
- client/src/pages/Home.js
- client/src/pages/LogIn.js
- client/src/pages/SignUp.js
Issue Number: #86 #108 #110
<br>
<br>
<br>
> [Client] 로그인, 회원가입 페이지, 메인 캐러셀 UI 구현

- server/src/main/java/server/team33/category/controller/CategoryController.java
- server/src/main/java/server/team33/item/controller/ItemController.java
- server/src/main/java/server/team33/item/dto/ItemDto.java
- server/src/main/java/server/team33/item/mapper/ItemMapper.java
- server/src/main/java/server/team33/item/repository/ItemRepository.java
- server/src/main/java/server/team33/item/service/ItemService.java
Issue Number: #106 
<br>
메인페이지에서 best 상품 9개와 sale 상품 9개를 조회할 수 있는 기능 구현
<br>
<br>
> [Server] 메인페이지에서 best 상품, sale 상품 9개씩 조회하기 

- server/src/main/java/server/team33/item/controller/ItemController.java
- server/src/main/java/server/team33/item/repository/ItemRepository.java
- server/src/main/java/server/team33/item/service/ItemService.java
Issue Number: #111 
<br>
- 아이템 키워드 검색 기능
- 아이템 가격 필터링
- 아이템 키워드 검색 + 가격 필터링 목록 조회
<br>
<br>
> [Server] 아이템 키워드 검색 및 가격 필터링 기능 구현 

- client/package-lock.json
- client/package.json
- client/src/components/Buttons/SearchButtons/PriceButton.js
- client/src/components/Buttons/SearchButtons/SortButton.js
- client/src/components/Buttons/WishlistButton.js
- client/src/components/Etc/Pagination.js
- client/src/components/Etc/Price.js
- client/src/components/Lists/DefaultList.js
- client/src/components/Lists/SmallListCards.js
- client/src/components/Lists/WishListCards.js
- client/src/pages/ItemList.js
- client/src/pages/MyPages/WishList.js
- client/src/pages/SearchList.js
Issue Number: #115 
<br>
- 일단 기본적으로 위시리스트 페이지의 UI를 구현했습니다. 또한 메인과 목록페이지에서 찜하기 기능이 삭제된 만큼 해당 페이지에 들어갈 List 컴포넌트에서 찜하기 버튼을 삭제했으며, 찜하기 버튼이 필요한 위시리스트 페이지에 넣을 WishListCard 컴포넌트를 새로 만들었습니다. 그리고 List컴포넌트 전부에게 Price컴포넌트를 붙였습니다. 다만, 현재 List 컴포넌트들이 불필요하게 많다고 생각되어, 나중에 리팩터링을 진행하면 어떨까 싶습니다.<br>
- axios를 설치습니다.<br>
- 목록 페이지에 들어가는 가격 검색 버튼에 할인상품 모아보기 버튼이 추가되었습니다. **_혹시 지환님께서는 이 컴포넌트에 대한 수정사항이 있으시다면 주의해주시기 바랍니다!!!!<br>_**
- 지환님이 작성중인 ItemLIst와 SearchList 페이지에 오류가 생기기 떄문에 주석처리를 했습니다. 다만, 지환님께서 오류가 나는 부분들을 json-server 로 옮기셨다고 하니, 지환님께서는 작업들을 stash로 보관하고 pull 받으신 후 stash pop으로 꺼내주시면 큰 이상이 없을 것이라 생각이 됩니다.
- 혹시 제가 놓친 사항이 있을 수 있으니 확인해주시기 바랍니다.  
<br>
<br>
> [Client] 마이페이지 - 위시리스트 페이지 UI 구현 

- server/src/main/java/server/team33/item/dto/ItemDto.java
- server/src/main/java/server/team33/item/mapper/ItemMapper.java
- server/src/main/java/server/team33/nutritionFact/dto/NutritionFactDto.java
<br>
아이템 영양성분 등록하기 기능 추가
<br>
<br>
> [Server] 영양성분 등록하기 기능 구현

- server/src/main/java/server/team33/category/controller/CategoryController.java
- server/src/main/java/server/team33/item/dto/ItemDto.java
- server/src/main/java/server/team33/item/repository/ItemRepository.java
- server/src/main/java/server/team33/item/service/ItemService.java
Issue Number: #128 
<br>
- 카테고리  + 가격필터 기능
- 카테고리 + 브랜드 + 가격필터 기능
- 카테고리 + 할인 + 가격필터 기능
- 카테고리 + 브랜드 + 할인 + 가격필터 기능 
<br> 
<br>
> [Server] 기능별 카테고리 기능 중첩 적용

- client/src/apis/login.js
- client/src/components/Caroucel/CardCaroucel.js
- client/src/components/Caroucel/MainCaroucel.js
- client/src/components/Etc/RecommendedTitle.js
- client/src/components/Inputs/AuthForm.js
- client/src/components/Inputs/AuthInput.js
- client/src/pages/Auth/LogIn.js
- client/src/pages/Auth/SignUp.js
- client/src/pages/Auth/SocialLogin.js
- client/src/pages/Main/Home.js
- client/src/pages/Main/MainSection.js
- client/src/redux/slice/userSlice.js
Issue Number: #108 #110
<br>
<br>
<br>
> [Client] 로그인, 메인 캐러셀 변경 

- server/src/main/java/server/team33/login/config/CustomFilterConfigurer.java
- server/src/main/java/server/team33/login/config/SecurityConfig.java
- server/src/main/java/server/team33/login/filter/JwtLoginFilter.java
- server/src/main/java/server/team33/login/handler/UserAuthSuccessHandler.java
- server/src/main/java/server/team33/payment/contoller/PaymentController.java
- server/src/main/java/server/team33/payment/dto/KakaoPayApproveDto.java
- server/src/main/java/server/team33/payment/service/SubsPayService.java
- server/src/main/java/server/team33/subscription/job/SubscriptionJob.java
- server/src/main/java/server/team33/user/controller/UserController.java
- server/src/main/java/server/team33/user/dto/UserDto.java
- server/src/main/java/server/team33/user/mapper/UserMapper.java
- server/src/main/java/server/team33/user/service/UserService.java
Issue Number: #5 #21
<br>
- jwt 로그인 시  토큰 발행 위치 수정
- 회원 정보 조회 시 소셜 로그인 회원 구분
<br>
<br>
> [Server] 일반 로그인시 토큰 발행 위치 수정, 회원 정보 조회 시 소셜 로그인한 회원 구분

- server/src/main/java/server/team33/item/dto/ItemDto.java
- server/src/main/java/server/team33/item/mapper/ItemMapper.java
- server/src/main/java/server/team33/order/controller/OrderController.java
- server/src/main/java/server/team33/order/reposiroty/OrderRepository.java
- server/src/main/java/server/team33/order/service/OrderService.java
- server/src/main/java/server/team33/wish/controller/WishController.java
- server/src/main/java/server/team33/wish/dto/WishDto.java
- server/src/main/java/server/team33/wish/mapper/WishMapper.java
- server/src/main/java/server/team33/wish/repository/WishRepository.java
- server/src/main/java/server/team33/wish/service/WishService.java
Issue Number: #144 #143 
<br>
- 정기 구독 중인 목록 조회
- 구독 목록에서 수량 변경
- 위시리스트에서 불러오는 목록 수정
<br>
<br>
> [Server] 정기 구독 목록 조회 기능 구현, 위시 리스트 조회 기능 수정

- server/src/main/java/server/team33/item/controller/ItemController.java
- server/src/main/java/server/team33/item/dto/ItemDto.java
- server/src/main/java/server/team33/item/mapper/ItemMapper.java
- server/src/main/java/server/team33/item/repository/ItemRepository.java
- server/src/main/java/server/team33/item/service/ItemService.java
Issue Number: #153 
<br>
<br>
메인페이지에서 MdPick(최근등록순)으로 9개의 상품을 모아볼 수 있는 기능
<br>
> [Server] MdPick(최신순) 모아보기 기능 구현 

- client/src/components/Etc/Price.js
- client/src/components/Etc/Tag.js
- client/src/pages/Detail.js
Issue Number: #155
<br>
- 상세페이지에 API를 적용하였습니다.
<br>
<br>
> [Client] 상세페이지 API 적용

- server/build.gradle
- server/src/main/java/server/team33/login/filter/JwtLoginFilter.java
- server/src/main/java/server/team33/login/handler/UserAuthSuccessHandler.java
- server/src/main/java/server/team33/user/service/UserService.java
- server/src/main/resources/application.yml
Issue Number: #5 #10
<br>
- 로그인 시 유저 아이디 제공
<br>
<br>
> [Server] 로그인 시 유저 아이디 제공 

- client/src/components/Forms/DefalutForm.js
- client/src/components/Lists/MyPageLists/MyPageReviewList.js
- client/src/components/Modals/ReviewModal.js
- client/src/hooks/useFetch.js
- client/src/hooks/useLogIn.js
- client/src/pages/Main/Home.js
- client/src/pages/MyPages/NoteReview.js
- client/src/pages/MyPages/UserInfo.js
- client/src/redux/slice/userSlice.js
Issue Number: #122 #138 #149
<br>
<br>
<br>
> [Client] 쿼리 invalidate, 로컬스토리지 토큰 불러오기

- server/src/main/java/server/team33/item/dto/ItemSimpleResponseDto.java
- server/src/main/java/server/team33/item/mapper/ItemMapper.java
- server/src/main/java/server/team33/order/controller/OrderController.java
- server/src/main/java/server/team33/order/service/ItemOrderService.java
- server/src/main/java/server/team33/order/service/OrderService.java
- server/src/main/java/server/team33/review/controller/ReviewController.java
- server/src/main/java/server/team33/review/dto/ReviewDetailResponseDto.java
- server/src/main/java/server/team33/review/entity/Review.java
- server/src/main/java/server/team33/review/mapper/ReviewMapper.java
Issue Number: #165 
<br>
- 리뷰에 아이템 구매 수량 정보 추가
<br>
<br>
> [Server] 리뷰에서 구매 수량을 확인할 수 있도록 quantity 필드 추가

- server/src/main/java/server/team33/item/service/ItemService.java
Issue Number: #168 
<br>
- 아이템 필터링 후 낮은 가격으로 정렬하는 기능을 추가했습니다.
<br>
<br>
> [Server] 아이템 목록 낮은가격순 정렬 기능 구현

- client/src/components/Etc/Tag.js
- client/src/components/Forms/DefalutForm.js
- client/src/components/ItemSummary/Summary.js
- client/src/components/Lists/MyPageLists/OrderDetailList.js
- client/src/components/Modals/ReviewModal.js
- client/src/components/Tabs/DefaultTabButton.js
- client/src/components/Tabs/TabButtons.js
- client/src/hooks/usePurchase.js
- client/src/pages/Detail.js
- client/src/pages/MyPages/NormalOrder.js
- client/src/pages/MyPages/OrderDetail.js
Issue Number:#170 #155
<br>
상세페이지 장바구니 담기, 바로 결제하기 API 적용
<br>
<br>
> [Client] 상세페이지 장바구니 담기, 바로 결제하기 API 적용

- server/src/main/java/server/team33/item/repository/ItemRepository.java
- server/src/main/java/server/team33/item/service/ItemService.java
Issue Number: #153 
<br>
<br> 
<br>
> [Server] 메인페이지 종류별 9개씩 불러오는 쿼리 수정

- client/src/components/Etc/DefaultPayment.js
- client/src/components/Etc/PayDestination.js
- client/src/components/Etc/PayInfo.js
- client/src/components/Etc/PayItemInformation.js
- client/src/components/Etc/PayMethod.js
- client/src/components/Etc/Price.js
- client/src/components/ItemSummary/Summary.js
- client/src/components/Lists/PayLists.js
- client/src/pages/Payment.js
- client/src/pages/SubPayment.js
Issue Number: #176
<br>
카카오 페이와 토스 페이먼츠를 이용한 결제 기능이 구현되었습니다.
<br>
<br>
> [Client] 결제기능 구현

- client/src/components/Etc/PayInfo.js
- client/src/components/Etc/Price.js
- client/src/components/Lists/MyPageLists/OrderDetailList.js
- client/src/components/Lists/MyPageLists/OrderList.js
- client/src/pages/MyPages/OrderDetail.js
Issue Number: #161 #100
<br>
- 가격 컴포넌트에 할인가 적용할 경우 컬러 등의 CSS 효과가 적용되지 않는 문제 해결하였습니다.
- 주문내역 페이지(일반) API 적용하였습니다.
- 주문내역 상세페이지 API 적용하였습니다.
<br>
<br>
> [Client] 마이페이지 주문내역 페이지, 주문내역 상세페이지 API 적용

- client/src/components/Buttons/WishlistButton.js
- client/src/hooks/useFetch.js
- client/src/pages/MyPages/OrderDetail.js
Issue Number: #161 #180
<br>
- 위시리스트 버튼 클릭 시, POST요청을 보낼 수 있도록 API 적용하였습니다.
- useGet에 isSuccess를 추가하였습니다.
- 주문내역 상세페이지의 가격 컴포넌트가 받는 가격 관련 props를 변경하였습니다.
<br>
<br>
> [Client] 위시리스트 버튼 API 적용

- client/src/components/Forms/UpdateTalkForm.js
- client/src/components/Lists/MyPageLists/CartList.js
- client/src/components/Lists/MyPageLists/MyPageReviewList.js
- client/src/components/Lists/MyPageLists/OrderDetailList.js
- client/src/components/Lists/PayLists.js
- client/src/components/Modals/CancelModal.js
- client/src/components/Modals/ReviewModal.js
- client/src/components/Modals/TalkModal.js
- client/src/components/Stars/BtnStar.js
- client/src/components/Stars/TextStar.js
- client/src/components/Tabs/DefaultTabButton.js
- client/src/components/Talk/MyPageTalk.js
- client/src/pages/Carts/NormalCart.js
- client/src/pages/Carts/SubCart.js
- client/src/pages/Main/Home.js
- client/src/pages/MyPage.js
- client/src/pages/MyPages/NoteReview.js
- client/src/pages/MyPages/NoteTalk.js
- client/src/pages/MyPages/OrderDetail.js
Issue Number: #89 #165
<br>
- 작성글관리 API 연결
- 장바구니 UI 개선
- 장바구니 API 연결
- 마이페이지 뒤로가기 방지
<br>
<br>
> [Client] 작성글관리, 장바구니 페이지 구현

- server/build.gradle
- server/src/main/java/server/team33/login/config/SecurityConfig.java
- server/src/main/java/server/team33/login/filter/JwtVerificationFilter.java
- server/src/main/java/server/team33/login/handler/UserAccessDeniedHandler.java
- server/src/main/java/server/team33/login/handler/UserAuthFailureHandler.java
- server/src/main/java/server/team33/login/handler/UserAuthenticationEntryPoint.java
- server/src/main/java/server/team33/payment/contoller/PaymentController.java
- server/src/main/java/server/team33/user/service/UserService.java
- server/src/main/resources/application.yml
Issue Number: #5 #10 #182
<br>
- api 권한 설정
- jwt 예외 처리 수정
<br>
<br>
> [Server] api 권한 설정,  jwt 예외 처리 수정

- server/src/main/java/server/team33/cart/controller/ItemCartController.java
- server/src/main/java/server/team33/cart/service/ItemCartService.java
- server/src/main/java/server/team33/order/controller/OrderController.java
- server/src/main/java/server/team33/order/dto/ItemOrderDto.java
- server/src/main/java/server/team33/order/mapper/ItemOrderMapper.java
- server/src/main/java/server/team33/order/reposiroty/ItemOrderRepository.java
- server/src/main/java/server/team33/order/service/ItemOrderService.java
- server/src/main/java/server/team33/order/service/OrderService.java
- server/src/main/java/server/team33/subscription/trigger/TriggerService.java
Issue Number: #187 
<br>
- 정기 구독 목록을 불러오는 메서드를 수정했습니다.
- 장바구니 목록 삭제 시 장바구니 내역이 리프레시 되도록 하는 기능을 수정했습니다.
<br>
<br>
> [Server] 정기 구독 목록 수정, 장바구니 항목 삭제 기능 수정

- client/.eslintrc.json
- client/src/components/Lists/MyPageLists/CartList.js
- client/src/components/Tabs/DefaultTabButton.js
- client/src/components/Tabs/TabButtons.js
Issue Number: #89
<br>
<br>
<br>
> [Client] 정기장바구니 배송주기 변경 API 연결, 탭버튼 수정

- client/src/components/Buttons/SearchButtons/SortButton.js
- client/src/components/Etc/LoadingSpinner.js
- client/src/components/Etc/Pagination.js
- client/src/components/Tabs/DefaultTabButton.js
- client/src/pages/Carts/NormalCart.js
- client/src/pages/Carts/SubCart.js
- client/src/pages/ItemList.js
- client/src/pages/Main/Home.js
- client/src/pages/SearchList.js
Issue Number: #89 #90 #192
<br>
- 페이지네이션
- 로딩스피너 컴포넌트 (Etc폴더에 있습니다.)
- 정렬버튼 찜 많은순 -> 구매순 메뉴 교체
<br>
<br>
> [Client] 목록, 검색목록 페이지네이션 구현 외

- client/package-lock.json
- client/package.json
- client/src/App.js
- client/src/components/Etc/Price.js
- client/src/components/Layout/LeftNav.js
- client/src/components/Layout/RightNav.js
- client/src/pages/Carts/NormalCart.js
- client/src/pages/Carts/SubCart.js
- client/src/pages/ItemList.js
Issue Number: #89 #90 #192
<br>
- App.js에서 타이틀을 설정했습니다
- 카테고리 명에 "/" 가 들어있어서 "관절/뼈 건강" 카테고리 아이템들이 요청되지 않는 이슈를 해결했습니다.
<br>
<br>
> [Client] 장바구니 구매 요청, 타이틀 설정 외

- client/src/components/Buttons/BlackButton.js
- client/src/components/Etc/MyPageHeader.js
- client/src/components/Etc/PayDestination.js
- client/src/components/Etc/PayInfo.js
- client/src/components/Etc/PayItemInformation.js
- client/src/components/Etc/PayMethod.js
- client/src/components/Lists/MyPageLists/OrderList.js
- client/src/components/Lists/MyPageLists/SubManagementList.js
- client/src/components/Lists/MyPageLists/Talk/MyPageTalk.js
- client/src/components/Lists/WishListCards.js
- client/src/components/Tabs/MypageTab.js
- client/src/pages/Main/Home.js
- client/src/pages/MyPages/NormalOrder.js
- client/src/pages/MyPages/NoteReview.js
- client/src/pages/MyPages/NoteTalk.js
- client/src/pages/MyPages/OrderDetail.js
- client/src/pages/MyPages/SubManage.js
- client/src/pages/MyPages/SubscriptionOrder.js
- client/src/pages/MyPages/UserInfo.js
- client/src/pages/MyPages/WishList.js
- client/src/pages/Payment.js
Issue Number: #192 
<br>
- 로딩 스피너를 달았습니다
- 토스 결제 후 리다이렉팅 되는 주소를 배포 주소로 바꿨습니다
- 제가 맡은 페이즈의 필요없는 주석들을 제거했습니다
- 정기구독 목록 삭제 시 모달이 닫히지 않는 현상을 고쳤습니다
<br>
<br>
> [Client] 리다이렉팅 주소 변경 및 오류 수정

- server/src/main/java/server/team33/order/service/ItemOrderService.java
- server/src/main/java/server/team33/subscription/controller/ScheduleController.java
- server/src/main/java/server/team33/subscription/service/SubscriptionService.java
- server/src/main/java/server/team33/user/service/UserInfoFilter.java
- server/src/main/java/server/team33/user/service/UserService.java
Issue Number: #22 #63
<br>
- 소셜 로그인 시 장바구니 생성
- 구독 취소시 itemOrder의 구독 상태 변경
<br>
<br>
> [Server] 소셜 로그인 시 장바구니 생성, 구독 취소시 itemOrder의 구독 상태 변경

- server/src/main/java/server/team33/item/controller/ItemController.java
- server/src/main/java/server/team33/item/entity/Item.java
- server/src/main/java/server/team33/item/service/ItemService.java
Issue Number: 
<br>
아이템 삭제 기능 추가구현 및 정렬 조건 변경
<br>
> [Server] 아이템 삭제 기능, 정렬 조건 변겅

- client/src/components/Caroucel/CardCaroucel.js
- client/src/components/Lists/MyPageLists/CartList.js
- client/src/components/Stars/TextStar.js
- client/src/pages/Auth/LogIn.js
- client/src/pages/Auth/SignUp.js
- client/src/pages/Main/Home.js
Issue Number: #192
<br>
- 별점이 소수점 1자리수에서 반올림 되었습니다
- 일부 리스트에서 브랜드 호버시 포인터로 커서가 바뀌었지만 이동하지 않기 때문에 기본 커서로 변경했습니다.
<br>
<br>
> [Client] 별점 소수점 절삭

- server/src/main/java/server/team33/order/reposiroty/OrderRepository.java
- server/src/main/java/server/team33/order/service/OrderService.java
Issue Number: #211 
<br>
주문 목록 리팩토링
<br>
<br>
> [Server]  주문 목록 리팩토링

- server/src/main/java/server/team33/order/service/ItemOrderService.java
- server/src/main/java/server/team33/subscription/controller/ScheduleController.java
- server/src/main/java/server/team33/subscription/job/KaKaoSubscriptionJob.java
- server/src/main/java/server/team33/subscription/job/SubscriptionJob.java
- server/src/main/java/server/team33/subscription/service/SubscriptionService.java
Issue Number: #63
<br>
- 여러 상품 정기 구독 시 다음 배송일 출력 수정
<br>
<br>
> [Server] 여러 상품 정기 구독 시 다음 배송일 출력 수정

- server/src/main/java/server/team33/order/reposiroty/ItemOrderRepository.java
- server/src/main/java/server/team33/payment/service/PayService.java
Issue Number: #211 
<br>
- 정기 구독 목록 조회 기능 수정
- 일반 결제 요청 헤더 수정
<br>
<br>
> [Server] 정기 구독 목록 조회 기능 수정, 일반 결제 요청 헤더 수정

- client/src/components/Buttons/WishlistButton.js
- client/src/components/Etc/PayMethod.js
- client/src/components/Lists/MyPageLists/SubManagementList.js
- client/src/components/Tabs/DefaultTabButton.js
- client/src/components/Tabs/TabButtons.js
- client/src/pages/MyPages/SubManage.js
- client/src/pages/MyPages/UserInfo.js
Issue Number: #192 
<br>
- api 변경에 따른 수정
- 유저정보수정 페이지 소셜/일반 회원 비밀번호 인풋 구분
- 정기구독관리 페이지 여백 조절
<br>
<br>
> [Client] 기타 수정사항(주석제거, api변경에 따른 수정,정기구독관리 페이지)

- client/src/components/Etc/PayMethod.js
Issue Number: #192 
<br>
토스 페이먼츠 일반 결제 버튼이 다시 생성되었습니다.
<br>
<br>
> [Client] 토스 페이먼츠 버튼 생성

- server/src/main/java/server/team33/order/reposiroty/OrderRepository.java
- server/src/main/java/server/team33/order/service/OrderService.java
- server/src/main/java/server/team33/payment/contoller/PaymentController.java
Issue Number: #223 
<br>
- 구매자 임을 확인하는 메서드 리팩토링
- 일반 결제 리다이렉팅 주소 수정
<br>
<br>
> [Server] 구매자임을 확인하는 메서드 리팩토링, 일반 결제 리다이렉팅 주소 수정

- client/src/components/Lists/DetailTalkList.js
- client/src/components/Lists/MainListCard.js
- client/src/pages/Detail.js
- client/src/pages/Main/Home.js
Issue Number: #192 #209 #217
<br>
- 토크 답변 작성 재클릭 시 작성 폼이 닫힙니다.
- 토크 작성하기 버튼의 화살표 방향을 수정하였습니다.
- 메인 카드 리스트에 영양성분을 표기하고 CSS를 수정하였습니다.
- 소셜로그인 시 url로 받아오는 userId를 스토어 및 로컬스토리지에 저장하였습니다.
- 불필요한 주석 및 코드를 삭제하였습니다. 
<br>
<br>
> [Client] 토크 및 이슈 #192 관련 수정 사항

- client/package-lock.json
- client/package.json
- client/src/apis/itemApis.js
- client/src/components/Buttons/SearchButtons/SortAndSearchButtons.js
- client/src/components/Caroucel/MainCaroucel.js
- client/src/components/Etc/PageTitle.js
- client/src/components/Inputs/AuthForm.js
- client/src/components/Lists/SmallListCards.js
- client/src/hooks/useGetList.js
- client/src/hooks/useLogIn.js
- client/src/pages/Auth/LogIn.js
- client/src/pages/Carts/SubCart.js
- client/src/pages/ItemList.js
- client/src/pages/Main/Home.js
- client/src/pages/NotFound.js
- client/src/pages/SearchList.js
- client/src/redux/slice/filterSlice.js
- client/src/utils/axiosInstance.js
Issue Number: #90 #122 #192 #222
<br>
- 무한 스크롤 구현
- 기타 버그 수정
- 주석, 콘솔로그 제거
<br>
<br>
> [Client] 무한 스크롤 구현 외

- client/src/components/Inputs/AuthInput.js
Issue Number: N/A
<br>
<br>
<br>
> 💄 style: 로그인 엔터 안내 반영 #192

- client/src/components/Lists/DetailReviewList.js
Issue Number: #242 
<br>
상세페이지 리뷰 삭제 기능이 추가되었습니다.
여태 안되고 있었답니다. 신기하죠? 저도 신기해요
<br>
<br>
> [Client] 상세페이지 리뷰 삭제 구현

- client/.eslintrc.json
- client/package-lock.json
- client/package.json
- client/src/index.tsx
- client/src/react-app-env.d.ts
- client/tsconfig.json
Issue Number: #244
<br>
<br>
<br>
> [Client] 타입스크립트 초기 세팅 중

- client/.eslintrc.json
- client/src/components/Stars/BtnStar.tsx
- client/src/components/Stars/TextStar.tsx
Issue Number: #253 
<br>
Star 컴포넌트들 타입스크립트 적용
<br>
<br>
> [Client] 타입스크립트 리팩터링 - Stars

- client/.eslintrc.json
- client/src/components/Forms/DefalutForm.tsx
- client/src/components/Forms/ReviewForm.tsx
- client/src/components/Forms/TalkForm.tsx
- client/src/components/Forms/UpdateTalkForm.tsx
- client/src/types/button.type.ts
- client/src/types/form.type.ts
Issue Number: 266
<br>
Forms 컴포넌트 리팩터링 하고 form.type.ts 생성했습니다.
<br>
<br>
> [Client] 타입스크립트 리팩터링 - Forms

- client/src/components/Lists/MyPageLists/MyPageReviewList.tsx
- client/src/components/Lists/MyPageLists/Talk/MyPageTalk.tsx
- client/src/pages/MyPages/NoteReview.tsx
- client/src/pages/MyPages/NoteTalk.tsx
- client/src/types/note.type.ts
Issue Number: #283 
<br>
2개의 페이지와
client/src/pages/MyPages/NoteReview.tsx
client/src/pages/MyPages/NoteTalk.tsx
2개의 컴포넌트에 타입을 적용했습니다.
client/src/components/Lists/MyPageLists/MyPageReviewList.tsx
client/src/components/Lists/MyPageLists/Talk/MyPageTalk.tsx
<br>
<br>
> [Client] 타입스크립트 리팩터링 - 장바구니 페이지

- server/src/main/java/server/team33/item/dto/ItemSimpleResponseDto.java
- server/src/main/java/server/team33/item/mapper/ItemMapper.java
Issue Number: #287 
<br>
- ItemSimpleResponseDto 의 필드 disCountPrice 를 discountPrice 로 수정했습니다.
- ItemMapper 의 disCountPrice 를 discountPrice 로 수정했습니다.
<br>
<br>
> [Server] ItemSimpleResponseDto 의 필드 수정 

- client/src/Router.tsx
- client/src/hooks/useFetch.ts
- client/src/pages/MyPages/UserProfile.tsx
Issue Number: #314 
<br>
유저정보조회 파일 이름바꾸고 타입스크립트로 이관했습니다
<br>
<br>
> [Client] 타입스크립트 리팩터링 -  유저정보조회
